# Generated by Django 2.0.5 on 2018-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
