# Generated by Django 2.0.5 on 2018-06-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessgames', '0004_auto_20180613_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatchannels.ChatChannel'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='chess_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessgames.ChessGame'),
        ),
    ]
