# Generated by Django 2.0.5 on 2018-05-24 18:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField()),
                ('history', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('admins', models.ManyToManyField(related_name='admin_channels', to=settings.AUTH_USER_MODEL)),
                ('allowed_participants', models.ManyToManyField(related_name='allowed_channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
